[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "church_bot"
version = "0.1.0"
dependencies = [
    "python-telegram-bot==20.7",
    "APScheduler==3.10.4", 
    "pytz==2024.1",
    "aiohttp==3.9.5"
]